MediaBundle\Entity\Commentaire:
    type: entity
    table: null
    repositoryClass: MediaBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        utilisateur:
            type: string
            length: 255
#
#    manyToOne:
#        commentaire:
#            targetEntity: MediaBundle\Entity\album
#            inversedBy: commentaires

    manyToOne:
        albums:
            targetEntity: MediaBundle\Entity\album

    lifecycleCallbacks: {  }
