media_album:
    resource: "@mediaBundle/Resources/config/routing/album.yml"
    prefix:   /

media_commentaire:
    resource: "@mediaBundle/Resources/config/routing/commentaire.yml"
    prefix:   /commentaire