media:
    resource: "@MediaBundle/Resources/config/routing/album.yml"
    prefix:   /

commentaire:
    resource: "@MediaBundle/Resources/config/routing/commentaire.yml"
    prefix:   /commentaire

media_homepage:
    path:     /
    defaults: { _controller: MediaBundle:Default:index }
