commentaire_index:
    path:     /
    defaults: { _controller: "MediaBundle:Commentaire:index" }
    methods:  GET

commentaire_show:
    path:     /{id}/show
    defaults: { _controller: "MediaBundle:Commentaire:show" }
    methods:  GET

commentaire_new:
    path:     /new/{id}
    defaults:
        _controller: "MediaBundle:Commentaire:new"
        id: null
    methods:  [GET, POST]

commentaire_delete:
    path:     /{id}/delete
    defaults: { _controller: "MediaBundle:Commentaire:delete" }
    methods:  DELETE
