MediaProjectBundle\Entity\Album:
    type: entity
    table: null
    repositoryClass: MediaProjectBundle\Repository\AlbumRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titreAlbum:
            type: string
            length: 255
            column: titre_album
        artiste:
            type: string
            length: 255
        genre:
            type: string
            length: 255
        support:
            type: string
            length: 255

    manyToOne:
        commentaires:
            targetEntity: MediaProjectBundle\Entity\Commentaire

    lifecycleCallbacks: {  }
